version: '3'
services:
  web:
    image: blackavgn/webserviceimage:webservice
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      POSTGRES_URL: "jdbc:postgresql://db:5432/postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - net
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432
    networks:
      - net
