version: '3'
services:
  web:
    image: blackavgn/webserviceimage:webservice
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      POSTGRES_URL: 
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    networks:
      - net
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    ports:
      - 5432:5432
    networks:
      - net
